# maximum number of items a player can have for sale
#
# you can add your own
#
# sell_limits:
#     your_mom: 250
#
# node would be lonelyshop.max.your_mom and users with that perm
# could sell 250 items, which is shockingly close what the scale showed
# before yo fat ugly momma broke it
#
sell_limits:
    newbie: 10
    citizen: 30
    regular: 60
    veteran: 120
    vip: 180
  
# database settings
database: 
    prefix: ls_
    hostname: localhost
    port: 3306
    database: lonelyshop
    username: lonelyshop
    password: lonelyshop