# maximum number of items a player can have for sale
#
# nodes are checked like lonelyshop.max.citizen
#
# limits:
#     citizen: 20
#
sell_limits:
    newbie: 10
    citizen: 30
    regular: 60
    veteran: 120
    vip: 180
  
# database settings - required
database: 
    prefix: ls_
    hostname: localhost
    port: 3306
    database: lonelyshop
    username: lonelyshop
    password: lonelyshop