name: LonelyShop
main: com.ne0nx3r0.lonelyshop.LonelyShopPlugin
version: '1.0a'
database: false
description: Global shops plugin
depend: [Vault]
commands:
    ls:
      description: Lonely shop commands
    buy:
      description: Lonely shop buy command
    sell:
      description: Lonely shop sell command
permissions:
  lonelyshop.buy:
    description: can buy items from lonelyshop
    default: false
  lonelyshop.sell:
    description: can sell items to lonelyshop
    default: false