name: LonelyShop
main: com.ne0nx3r0.lonelyshop.LonelyShopPlugin
version: '1.5b'
database: false
description: Global shops plugin
depend: [Vault]
commands:
    ls:
      description: Lonely shop commands
    buy:
      description: Buy items from the global shop
    sell:
      description: Sell an item to the global shop
    shop:
      description: Open your own shop
permissions:
  lonelyshop.buy:
    description: can buy items from lonelyshop
    default: false
  lonelyshop.sell:
    description: can sell items to lonelyshop
    default: false
  lonelyshop.shop:
    description: Open your for sale items screen
    default: false